version: "3"

services:
  proxy:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx.template.conf:/etc/nginx/nginx.conf.template:ro
      - ./ssl:/etc/ssl/certs/:ro
    restart: always
    ports:
      - 443:443
    environment:
      - PROJECT_PORT=3000
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
